Lesson:  How to Handle Errors using Async Pipe  (approach 2)
------------------------------------------------------------


In your TypeScript code
-----------------------
this.state$ = request.pipe(map(users => {users, error: null}), catchError(error => {users: null, error})).pipe(startWith({users: null, error: null}));


In your Template
-----------------
<ng-container *ngif="state$ | async as state">

<div *ngif="!state.users &amp;&amp; !state.error">
Loading users...
</div>

<div *ngif="state.error">
{{state.error}}
</div>

<ng-container *ngif="state.users">
<div *ngfor="let user of state.users">
{{ user.name }}
</div>
</ng-container>

<ng-container>

